version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/Berlin"
    versioning-strategy: "increase"
    reviewers:
      - "alexanderniebuhr"
    labels:
      - "dependencies"